title: Here lives a winter bear
description: Share what Bear has learned
social_link: ''
social_username: ''
github_repo: winterbear
github_username: WinterFor
theme_color: light
remote_theme: internet-de-france/athena
baseurl: /winterbear
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - light
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
